### ISSUE TITLE
Separate the Firstname and lastname for desktop version

### ISSUE THREAD

**Issue by prius2055** [abeltsew/portfolio#10]
Nice job Abel. I like the way your page is beautifully laid out and the animations, they are fantastic.

Just a little observation though,

- The first name should have a separate input field
- The last name should also have its own input field

You can check out the Figma design for the desktop version for more understanding.

**Comment by abeltsew** [comment]
Hi @prius2055 ,

I just realized that there is the below note in the instructions.

IMPORTANT NOTE some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in Contact me or Get in touch sections). Please ignore this part of the design template and use only one input for the full name for all versions.
