### ISSUE TITLE
Portfolio project review

### ISSUE THREAD

**Issue by Jeddaa** [abeltsew/portfolio#3]
- Well done! You did a very good job but the margin between some of your sections is more than the required in the figma design.
- For example, the header section has a bigger gap than required between it and the works section.
- Also try to create individual CSS files for each section to avoid very long style.css file which could lead to confusion later on as the project is being modified.
- Overall, you did a very good job. Kudos to you!

**Comment by abeltsew** [comment]
All Issues have been Addressed
